### ISSUE TITLE
Complex constraint values leaking into problem summary

### ISSUE THREAD

**Issue by gjkennedy** [mdolab/pyoptsparse#101] opened 2020-05-04 18:17 UTC
#65  Description
Complex components printed out in constraint components of the problem summary.

### Steps to reproduce issue
1. Run one of the example problems: hs071.py, hs015.py etc.

### Current behavior
The constraint value contains a complex component, even though these problems are posed using real arithmetic. The complex part from the complex-step is leaking into the results.

### Expected behavior
The constraint values should be real.

**Comment by nwu63** [comment] 2020-05-04 18:26
Hi Graeme,

This is likely a duplicate of #76. I plan to go through the code at some point, and fix all the casting:
- real/complex
- scalar/numpy array

Is this breaking anything or causing any issues on your end? If so then I can try to prioritize this and push up a fix soon, but I do have other things on my plate at the moment.

**Comment by gjkennedy** [comment] 2020-05-04 19:27
Complex numbers do not have wide support within different optimizers and are not part of the generic pyOptSparse interface per se. They're used here to obtain the derivative, but that should be nearly transparent to the user. The optimized point is real, its complex components are artifacts. I think discarding the real part is necessary as described in #76, but this proposal is a bit simpler.

I've created a simple fix for the print summary on a branch and created a pull request with the modification.

--
Graeme J. Kennedy, PhD
Assistant Professor
School of Aerospace Engineering
Georgia Institute of Technology
270 Ferst Dr, Atlanta, GA 30332-0150
http://gkennedy.gatech.edu<http://gkennedy.gatech.edu/>


________________________________

**Comment by nwu63** [comment] 2020-05-04 21:44
Yep I agree with everything you said. For now #102 will deal with the printing, but I will try to address #76 at a later time. The user should not see any difference between FD and CS gradients except that CS will yield potentially better results.

**Closed** 2020-05-05 18:28 UTC
