### ISSUE TITLE
Duplicate entries in IPOPT history files

### ISSUE THREAD

**Issue by A-Gray-94** [mdolab/pyoptsparse#238] opened 2021-04-25 02:09 UTC
## Description
History files saved when using IPOPT appear to contain duplicate function and gradient evaluation entries

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_

1. Run `test_hs015.py` in test directory
2. Check `hs015_IPOPT.out`, IPOPT claims to have only performed 12 function evaluations and 11 gradient evaluations
3. Open the history file in python and inspect the `db` dictionary

### Current behavior
There are 47 stored function and gradient evaluations, that's 2x what IPOPT claims + 1

![Screenshot from 2021-04-24 22-11-12](https://user-images.githubusercontent.com/20371123/115977913-21e8cd00-a54a-11eb-9aea-f44eae611369.png)

### Expected behavior
There should be 12 function evaluation entries and 11 gradient evaluation entries

My suspicion is that IPOPT makes separate calls for evaluating the objective and the constraints at the same design point and pyoptsparse is currently writing a separate history entry for each one when it should be combining them. Same for the objective and constraint gradient evaluations

### Code versions
2.6.0

**Comment by nwu63** [comment] 2021-04-25 02:14
This is a known problem and a duplicate of #182, so I'm going to close this and redirect discussions over there.

**Closed by nwu63** 2021-04-25 02:14 UTC
Labels: bug
